site_name: 蟒营™ Maker 入门班
copyright: ©101camp 2020

theme: 
  name: 'simplex'
  custom_dir: '_theme/bootswatch/simplex'

nav:
  - Home: index.md
  - FAQ: faq.md
  - License: license.md

#  - ANN: announce.md
#  - User Guide: guide.md

markdown_extensions:
  - toc:
      permalink: "¶"

extra:
  logo: img/101camp_bauhaus_v3h32.png
  include_toc: yes
  extra_nav_links:
    Fork me on GitHub: https://github.com/101camp/mk

